public static class G {

	public const string TEXT_ID_MAIN_MENU_LOAD_GAME_BUTTON = "MAIN_MENU_LOAD_GAME_BUTTON";
	public const string TEXT_ID_MAIN_MENU_NEW_GAME_BUTTON = "MAIN_MENU_NEW_GAME_BUTTON";
	public const string TEXT_ID_MAIN_MENU_OPTIONS_BUTTON = "MAIN_MENU_OPTIONS_BUTTON";
	public const string TEXT_ID_MAIN_MENU_QUIT_BUTTON = "MAIN_MENU_QUIT_BUTTON";
	
	public const string TEXT_ID_QUIT_DIALOG_CANCEL_BUTTON = "QUIT_DIALOG_CANCEL_BUTTON";
	public const string TEXT_ID_QUIT_DIALOG_CONFIRMATION_BUTTON = "QUIT_DIALOG_CONFIRMATION_BUTTON";
	public const string TEXT_ID_QUIT_DIALOG_TITLE = "QUIT_DIALOG_TITLE";

	public const string ROOM_ID_LABORATORY = "Laboratory";

}
