public static class G {

	public const float SCREEN_ASPECT_RATIO = 16f / 9f;
	public const float SCREEN_HEIGHT = 900;
	public const int SCREEN_PIXELS_PER_UNIT = 100;

	public const string ROOM_ID_LABORATORY = "Laboratory";
	
	public const float CONFIRMATION_DIALOG_BUTTON_HEIGHT = 30;
	public const float CONFIRMATION_DIALOG_BUTTON_WIDTH = 120;
	public const float CONFIRMATION_DIALOG_HEIGHT = 120;
	public const float CONFIRMATION_DIALOG_PADDING = 16;
	public const float CONFIRMATION_DIALOG_WIDTH = 300;
	
	public const float MENU_BUTTON_HEIGHT = 30;
	public const float MENU_BUTTON_WIDTH = 120;

	public const string TEXT_ID_MAIN_MENU_LOAD_GAME_BUTTON = "MAIN_MENU_LOAD_GAME_BUTTON";
	public const string TEXT_ID_MAIN_MENU_NEW_GAME_BUTTON = "MAIN_MENU_NEW_GAME_BUTTON";
	public const string TEXT_ID_MAIN_MENU_OPTIONS_BUTTON = "MAIN_MENU_OPTIONS_BUTTON";
	public const string TEXT_ID_MAIN_MENU_QUIT_BUTTON = "MAIN_MENU_QUIT_BUTTON";
	
	public const string TEXT_ID_PAUSE_MENU_RESUME_BUTTON = "PAUSE_MENU_RESUME_BUTTON";

	public const string TEXT_ID_QUIT_DIALOG_CANCEL_BUTTON = "QUIT_DIALOG_CANCEL_BUTTON";
	public const string TEXT_ID_QUIT_DIALOG_CONFIRMATION_BUTTON = "QUIT_DIALOG_CONFIRMATION_BUTTON";
	public const string TEXT_ID_QUIT_DIALOG_LABEL = "QUIT_DIALOG_LABEL";
	public const string TEXT_ID_QUIT_DIALOG_TITLE = "QUIT_DIALOG_TITLE";

}
